import { Inter } from 'next/font/google';
import './globals.css';
import Navbar from './components/navbar';
const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div
          style={{ backgroundSize: '150rem' }}
          className="w-screen h-screen   bg-[url('/bg.jpg')] inset-0 bottom-10 bg-bottom bg-no-repeat bg-slate-50"
        >
          <div className="h-24">
            <Navbar />
          </div>
          <div className="h-[calc(100vh-6rem)]">{children}</div>
        </div>
      </body>
    </html>
  );
}
